services:
  postgres:
    image: postgres:17
    container_name: postgres_restore
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./events.backup:/backup/events.backup:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -d events"]
      interval: 5s
      retries: 20

  restore:
    image: postgres:17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./events.backup:/backup/events.backup:ro
    entrypoint: >
      bash -c "
        echo 'üöÄ Restauration du backup...' &&
        pg_restore -h postgres -U postgres -d events --verbose /backup/events.backup &&
        echo '‚úÖ Restauration termin√©e' || (echo '‚ùå √âchec restore' && exit 1)
      "

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true            # DEV: pas d'auth
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g        # Heap 1 Go (ajuste selon ta RAM)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"   # API
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - OPENSEARCH_SECURITY_DISABLED=true         # match plugins.security.disabled
    ports:
      - "5601:5601"   # UI
    depends_on:
      - opensearch


volumes:
  pgdata:
  opensearch-data:

