services:
  postgres:
    image: postgres:17
    container_name: postgres_restore
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./events-bis.backup:/backup/events-bis.backup:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 20

  restore:
    image: postgres:17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./events-bis.backup:/backup/events-bis.backup:ro
    entrypoint: >
      bash -c "
        echo 'üöÄ Restauration du backup...' &&
        pg_restore -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} --verbose /backup/events-bis.backup &&
        echo '‚úÖ Restauration termin√©e' || (echo '‚ùå √âchec restore' && exit 1)
      "


  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
      - I18N_LOCALE=en
    ports:
      - "5601:5601"
    depends_on:
      - opensearch


  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - opensearch
    environment:
      - OS_HOST=${OS_HOST}
      - OS_PORT=${OS_PORT}
      - OS_USER=${OS_USER}
      - OS_PASSWORD=${OPENSEARCH_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./back:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: next-static-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend


volumes:
  pgdata:
  opensearch-data:

